apiVersion: v1
kind: PersistentVolume
metadata:
  name: zeppelin-pv
  labels:
    type: local
spec:
  storageClassName: zeppelin-sc-host
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/ruizhou/work/spark/spark_practice/notebook/"

---
# pvc

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # This name uniquely identifies the PVC. This is used in deployment.
  name: zeppelin-pv-claim
spec:
  # Read more about access modes here: http://kubernetes.io/docs/user-guide/persistent-volumes/#access-modes
  accessModes:
    # The volume is mounted as read-write by a single node
    - ReadWriteOnce
  resources:
    # This is the request for storage. Should be available in the cluster.
    requests:
      storage: 5Gi
  storageClassName: "zeppelin-sc-host"

